// Solana DEPLOY.md header — title + provenance. Mirrors the EVM header but the
// provenance names the Anchor target instead of solc/@oz (those are EVM-only).

import { readOwnVersion } from "../../../lib/version.js";
import type { DeployMeta } from "../../types.js";

export function solanaHeader(meta: DeployMeta, now: Date = new Date()): string {
  const smartc = readOwnVersion();
  const date = now.toISOString().slice(0, 10);
  return [
    `# Deploy: ${meta.contractName}`,
    "",
    `> Generated by smartc ${smartc} · Solana SPL (Anchor 0.30.x) · ${date}`,
  ].join("\n");
}
