import { describe, it, expect } from "vitest";
import { generateDeployDoc, deployDocPath } from "../../src/deploy/index.js";
import {
  erc20ConstructorArgs,
  erc721ConstructorArgs,
  erc1155ConstructorArgs,
} from "../../src/deploy/constructorArgs.js";
import { centralizationWarnings } from "../../src/deploy/warnings.js";
import type { DeployFlags, DeployMeta } from "../../src/deploy/types.js";

// Golden-snapshot + per-section assertions (D-12). DeployMeta is built inline
// here (05-03's per-template deployMeta.ts does not exist yet) using the 05-01
// builders + centralizationWarnings. The frozen `now` makes the header date
// deterministic so the snapshots are stable.

const FROZEN = new Date("2026-05-29T00:00:00Z");

function makeMeta(
  contractName: string,
  standard: "erc20" | "erc721" | "erc1155",
  flags: DeployFlags,
): DeployMeta {
  const constructorArgs =
    standard === "erc20"
      ? erc20ConstructorArgs(flags)
      : standard === "erc721"
        ? erc721ConstructorArgs(flags)
        : erc1155ConstructorArgs(flags);
  return {
    contractName,
    chain: "evm",
    standard,
    constructorArgs,
    flags,
    warnings: centralizationWarnings({ standard, flags }),
  };
}

const erc20Bare = makeMeta("MyToken", "erc20", {
  mintable: false,
  burnable: false,
  pausable: false,
  access: "none",
  premintNonZero: true,
});
const erc20AllFlags = makeMeta("MyToken", "erc20", {
  mintable: true,
  burnable: true,
  pausable: true,
  access: "roles",
  premintNonZero: true,
});
const erc721AllFlags = makeMeta("MyNFT", "erc721", {
  mintable: true,
  burnable: true,
  pausable: true,
  access: "roles",
  enumerable: true,
  royalty: true,
});
const erc1155AllFlags = makeMeta("MyMulti", "erc1155", {
  mintable: true,
  burnable: true,
  pausable: true,
  access: "roles",
  supply: true,
  updatableUri: true,
});

describe("generateDeployDoc — golden snapshots (D-12)", () => {
  it("erc20-bare matches committed snapshot", async () => {
    const { content } = generateDeployDoc(erc20Bare, { now: FROZEN });
    await expect(content).toMatchFileSnapshot(
      "../fixtures/deploy/erc20-bare.DEPLOY.md",
    );
  });
  it("erc20-all-flags matches committed snapshot", async () => {
    const { content } = generateDeployDoc(erc20AllFlags, { now: FROZEN });
    await expect(content).toMatchFileSnapshot(
      "../fixtures/deploy/erc20-all-flags.DEPLOY.md",
    );
  });
  it("erc721-all-flags-with-royalty matches committed snapshot", async () => {
    const { content } = generateDeployDoc(erc721AllFlags, { now: FROZEN });
    await expect(content).toMatchFileSnapshot(
      "../fixtures/deploy/erc721-all-flags-with-royalty.DEPLOY.md",
    );
  });
  it("erc1155-all-flags matches committed snapshot", async () => {
    const { content } = generateDeployDoc(erc1155AllFlags, { now: FROZEN });
    await expect(content).toMatchFileSnapshot(
      "../fixtures/deploy/erc1155-all-flags.DEPLOY.md",
    );
  });
});

describe("generateDeployDoc — per-section content (DEPLOY-02/03/04/06/07/08)", () => {
  const all = [erc20Bare, erc20AllFlags, erc721AllFlags, erc1155AllFlags];

  for (const meta of all) {
    it(`${meta.standard}/${meta.contractName} has all section headers + key snippets`, () => {
      const { content } = generateDeployDoc(meta, { now: FROZEN });
      expect(content).toContain(`# Deploy: ${meta.contractName}`);
      expect(content).toContain("Generated by smartc");
      expect(content).toContain("## ⚠ Centralization Warnings");
      expect(content).toContain("## Pre-Deploy Safety Checklist");
      expect(content).toContain("## Deploy via Remix");
      expect(content).toContain("## Deploy via Hardhat");
      expect(content).toContain("## Deploy via Foundry");
      expect(content).toContain("## Verify on Etherscan");
      expect(content).toContain("## Constructor Arguments");
      // DEPLOY-03: forge create must include --broadcast
      expect(content).toContain("--broadcast");
      // DEPLOY-07: full solc version (Etherscan needs the commit hash)
      expect(content).toContain("v0.8.35+commit.47b9dedd");
      // DEPLOY-04: Remix open+paste, no local deep-link
      expect(content).toContain("remix.ethereum.org");
      expect(content).not.toContain("#url=file");
      // header date is the frozen date
      expect(content).toContain("2026-05-29");
    });
  }

  it("erc20-bare shows a single `recipient` ctor arg and no --constructor-args is fine", () => {
    const { content } = generateDeployDoc(erc20Bare, { now: FROZEN });
    expect(erc20Bare.constructorArgs.map((a) => a.name)).toEqual(["recipient"]);
    expect(content).toContain("--constructor-args <YOUR_WALLET_ADDRESS>");
  });

  it("erc20-all-flags (roles) shows 4 ctor args + roles-multi-key info warning (no mintable-ownable critical)", () => {
    const { content } = generateDeployDoc(erc20AllFlags, { now: FROZEN });
    expect(erc20AllFlags.constructorArgs.map((a) => a.name)).toEqual([
      "recipient",
      "defaultAdmin",
      "pauser",
      "minter",
    ]);
    expect(content).toContain("AccessControl — multiple privileged roles");
    expect(content).not.toContain("a single key can mint unlimited tokens");
  });

  it("erc721-all-flags-with-royalty (roles) shows roles-multi-key and a royalty checklist item", () => {
    const { content } = generateDeployDoc(erc721AllFlags, { now: FROZEN });
    expect(content).toContain("AccessControl — multiple privileged roles");
    expect(content).toContain("royalty recipient address and basis points");
  });

  it("erc1155-all-flags always shows the owner-controlled URI warning", () => {
    const { content } = generateDeployDoc(erc1155AllFlags, { now: FROZEN });
    expect(content).toContain("ERC-1155 default-URI setter is owner-controlled");
  });

  it("zero-arg meta: foundry/etherscan omit --constructor-args, hardhat uses .deploy()", () => {
    const zeroMeta = makeMeta("Bare", "erc721", {
      mintable: false,
      burnable: false,
      pausable: false,
      access: "none",
    });
    expect(zeroMeta.constructorArgs).toEqual([]);
    const { content } = generateDeployDoc(zeroMeta, { now: FROZEN });
    expect(content).not.toContain("--constructor-args");
    expect(content).toContain(".deploy();");
    expect(content).toContain("This contract has a no-argument constructor.");
  });

  it("no rendered doc contains a 0x-prefixed address literal — T-05-01", () => {
    for (const meta of [...all]) {
      const { content } = generateDeployDoc(meta, { now: FROZEN });
      expect(content).not.toMatch(/0x[0-9a-fA-F]{40}/);
    }
  });
});

describe("deployDocPath", () => {
  it("swaps a trailing .sol for .DEPLOY.md", () => {
    expect(deployDocPath("/x/MyToken.sol")).toBe("/x/MyToken.DEPLOY.md");
  });
  it("is case-insensitive on .SOL", () => {
    expect(deployDocPath("/x/MyToken.SOL")).toBe("/x/MyToken.DEPLOY.md");
  });
  it("appends when there is no .sol suffix", () => {
    expect(deployDocPath("/x/Custom")).toBe("/x/Custom.DEPLOY.md");
  });
});

describe("generateDeployDoc — registry + filename", () => {
  it("filename is <contractName>.DEPLOY.md", () => {
    expect(generateDeployDoc(erc20Bare, { now: FROZEN }).filename).toBe(
      "MyToken.DEPLOY.md",
    );
  });
});
