// DEPLOY.md header — title + provenance line (D-11).
// The attribution Phase 2 deferred lives HERE, not in the .sol (the .sol stays
// byte-for-byte OZ wizard output). Reads smartc/solc/@oz versions; the date is
// injectable so golden snapshots are deterministic.

import { readOwnVersion, safeReadVersion } from "../../lib/version.js";
import type { DeployMeta } from "../types.js";

export function header(meta: DeployMeta, now: Date = new Date()): string {
  const smartc = readOwnVersion();
  const solc = safeReadVersion("solc") ?? "unknown";
  const oz = safeReadVersion("@openzeppelin/contracts") ?? "unknown";
  const date = now.toISOString().slice(0, 10);
  return [
    `# Deploy: ${meta.contractName}`,
    "",
    `> Generated by smartc ${smartc} · solc ${solc} · @openzeppelin/contracts ${oz} · ${date}`,
  ].join("\n");
}
